Update README.md
viur-framework/awesome-viur pull request #7
Opened 2022-09-06 06:37 UTC by theVAX

Added the WSL and Container to the List

2022-09-06 13:42 UTC, sveneberth requested changes

2022-09-06 13:42 UTC, sveneberth commented on README.md
> +- [ViUR-WSL](https://github.com/Grashalmbeisser/viur-wsl-automated-setup) - The ViUR WSL Automated Setup project is a set of scripts that can make the installation and creation of an developerfriendl
This repo is not a official ViUR resource and should be moved to the section _Third-Party Resources_. Or we transfer/fork the repo with the viur-framework organization.

2022-09-06 14:08 UTC, phorward requested changes

2022-09-06 14:08 UTC, phorward commented on README.md
> +- [ViUR-WSL](https://github.com/Grashalmbeisser/viur-wsl-automated-setup) - The ViUR WSL Automated Setup project is a set of scripts that can make the installation and creation of an developerfriendl
- "Automated Setup" should stay in lower cas order
- "developerfriendly" is not an english adjective
- it is "a" developer friendly, not "an"

2022-09-06 14:08 UTC, phorward commented on README.md
> +- [ViUR-Container](https://github.com/viur-framework/viur-container/pkgs/container/viur3-container) Developerfriendly ViUR environment in a Docker Container
Same here, there is no developerfriendly

2022-09-09 10:50 UTC, XeoN-GHMB approved these changes

2022-09-09 10:54 UTC, sveneberth approved these changes

2022-09-09 10:55 UTC, merged